name: CI

on:
  pull_request:
  push:
    branches:
      - master

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - uses: DeterminateSystems/flake-checker-action@main
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            cores = 0

      - uses: cachix/cachix-action@v16
        with:
          name: nloge-cache
          authToken: '${{ secrets.CACHIX_TOKEN }}'

      - uses: rrbutani/use-nix-shell-action@v1

      - name: Check format
        run: |
          git ls-files '*.nix' | xargs nix fmt
          dune fmt
          git diff --exit-code
          actionlint

      - name: Build
        run: dune build

      - name: Test
        run: dune test
