name: Main workflow

on:
  pull_request:
  push:
    branches-ignore:
      - "**"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions: read-all
env:
  OCAML_COMPILER: "5.0"

jobs:
  publish:
    strategy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ env.OCAML_COMPILER }}
      - run: opam publish tag ${{ env.RELEASE_VERSION }}
